// src/constants/airports.ts

interface Airport {
  code: string; // IATA code: "SFO"
  name: string; // Full name: "San Francisco International Airport"
  city?: string;
  country?: string;
  timezone: string; // IANA timezone: "America/Los_Angeles"
}

// --------------------------------------
// Primary Mapping: Code -> Airport
// --------------------------------------

export const AIRPORTS_BY_CODE: Record<string, Airport> = {
  // --- United States: Major Hubs ---
  ATL: {
    code: "ATL",
    name: "Hartsfield–Jackson Atlanta International Airport",
    city: "Atlanta",
    country: "US",
    timezone: "America/New_York",
  },
  LAX: {
    code: "LAX",
    name: "Los Angeles International Airport",
    city: "Los Angeles",
    country: "US",
    timezone: "America/Los_Angeles",
  },
  ORD: {
    code: "ORD",
    name: "O'Hare International Airport",
    city: "Chicago",
    country: "US",
    timezone: "America/Chicago",
  },
  DFW: {
    code: "DFW",
    name: "Dallas/Fort Worth International Airport",
    city: "Dallas–Fort Worth",
    country: "US",
    timezone: "America/Chicago",
  },
  DEN: {
    code: "DEN",
    name: "Denver International Airport",
    city: "Denver",
    country: "US",
    timezone: "America/Denver",
  },
  JFK: {
    code: "JFK",
    name: "John F. Kennedy International Airport",
    city: "New York",
    country: "US",
    timezone: "America/New_York",
  },
  EWR: {
    code: "EWR",
    name: "Newark Liberty International Airport",
    city: "Newark",
    country: "US",
    timezone: "America/New_York",
  },
  SFO: {
    code: "SFO",
    name: "San Francisco International Airport",
    city: "San Francisco",
    country: "US",
    timezone: "America/Los_Angeles",
  },
  SEA: {
    code: "SEA",
    name: "Seattle–Tacoma International Airport",
    city: "Seattle",
    country: "US",
    timezone: "America/Los_Angeles",
  },
  LAS: {
    code: "LAS",
    name: "Harry Reid International Airport",
    city: "Las Vegas",
    country: "US",
    timezone: "America/Los_Angeles",
  },
  BOS: {
    code: "BOS",
    name: "Logan International Airport",
    city: "Boston",
    country: "US",
    timezone: "America/New_York",
  },
  IAH: {
    code: "IAH",
    name: "George Bush Intercontinental Airport",
    city: "Houston",
    country: "US",
    timezone: "America/Chicago",
  },
  HOU: {
    code: "HOU",
    name: "William P. Hobby Airport",
    city: "Houston",
    country: "US",
    timezone: "America/Chicago",
  },
  MIA: {
    code: "MIA",
    name: "Miami International Airport",
    city: "Miami",
    country: "US",
    timezone: "America/New_York",
  },
  SAN: {
    code: "SAN",
    name: "San Diego International Airport",
    city: "San Diego",
    country: "US",
    timezone: "America/Los_Angeles",
  },
  DCA: {
    code: "DCA",
    name: "Ronald Reagan Washington National Airport",
    city: "Washington, D.C.",
    country: "US",
    timezone: "America/New_York",
  },
  IAD: {
    code: "IAD",
    name: "Washington Dulles International Airport",
    city: "Washington, D.C.",
    country: "US",
    timezone: "America/New_York",
  },
  BWI: {
    code: "BWI",
    name: "Baltimore/Washington International Airport",
    city: "Baltimore",
    country: "US",
    timezone: "America/New_York",
  },
  MSP: {
    code: "MSP",
    name: "Minneapolis–Saint Paul International Airport",
    city: "Minneapolis–Saint Paul",
    country: "US",
    timezone: "America/Chicago",
  },
  DTW: {
    code: "DTW",
    name: "Detroit Metropolitan Airport",
    city: "Detroit",
    country: "US",
    timezone: "America/Detroit",
  },
  PHL: {
    code: "PHL",
    name: "Philadelphia International Airport",
    city: "Philadelphia",
    country: "US",
    timezone: "America/New_York",
  },
  CLT: {
    code: "CLT",
    name: "Charlotte Douglas International Airport",
    city: "Charlotte",
    country: "US",
    timezone: "America/New_York",
  },
  PHX: {
    code: "PHX",
    name: "Phoenix Sky Harbor International Airport",
    city: "Phoenix",
    country: "US",
    timezone: "America/Phoenix",
  },
  SLC: {
    code: "SLC",
    name: "Salt Lake City International Airport",
    city: "Salt Lake City",
    country: "US",
    timezone: "America/Denver",
  },
  HNL: {
    code: "HNL",
    name: "Daniel K. Inouye International Airport",
    city: "Honolulu",
    country: "US",
    timezone: "Pacific/Honolulu",
  },

  // --- U.S. secondary & regional with frequent use ---
  OAK: {
    code: "OAK",
    name: "Oakland International Airport",
    city: "Oakland",
    country: "US",
    timezone: "America/Los_Angeles",
  },
  SJC: {
    code: "SJC",
    name: "San José Mineta International Airport",
    city: "San Jose",
    country: "US",
    timezone: "America/Los_Angeles",
  },
  LGA: {
    code: "LGA",
    name: "LaGuardia Airport",
    city: "New York",
    country: "US",
    timezone: "America/New_York",
  },
  FLL: {
    code: "FLL",
    name: "Fort Lauderdale–Hollywood International Airport",
    city: "Fort Lauderdale",
    country: "US",
    timezone: "America/New_York",
  },
  TPA: {
    code: "TPA",
    name: "Tampa International Airport",
    city: "Tampa",
    country: "US",
    timezone: "America/New_York",
  },
  MCO: {
    code: "MCO",
    name: "Orlando International Airport",
    city: "Orlando",
    country: "US",
    timezone: "America/New_York",
  },
  RSW: {
    code: "RSW",
    name: "Southwest Florida International Airport",
    city: "Fort Myers",
    country: "US",
    timezone: "America/New_York",
  },
  AUS: {
    code: "AUS",
    name: "Austin–Bergstrom International Airport",
    city: "Austin",
    country: "US",
    timezone: "America/Chicago",
  },
  RDU: {
    code: "RDU",
    name: "Raleigh–Durham International Airport",
    city: "Raleigh–Durham",
    country: "US",
    timezone: "America/New_York",
  },
  STL: {
    code: "STL",
    name: "St. Louis Lambert International Airport",
    city: "St. Louis",
    country: "US",
    timezone: "America/Chicago",
  },
  CMH: {
    code: "CMH",
    name: "John Glenn Columbus International Airport",
    city: "Columbus",
    country: "US",
    timezone: "America/New_York",
  },
  CLE: {
    code: "CLE",
    name: "Cleveland Hopkins International Airport",
    city: "Cleveland",
    country: "US",
    timezone: "America/New_York",
  },
  CVG: {
    code: "CVG",
    name: "Cincinnati/Northern Kentucky International Airport",
    city: "Cincinnati",
    country: "US",
    timezone: "America/New_York",
  },
  IND: {
    code: "IND",
    name: "Indianapolis International Airport",
    city: "Indianapolis",
    country: "US",
    timezone: "America/Indiana/Indianapolis",
  },
  JAX: {
    code: "JAX",
    name: "Jacksonville International Airport",
    city: "Jacksonville",
    country: "US",
    timezone: "America/New_York",
  },
  BNA: {
    code: "BNA",
    name: "Nashville International Airport",
    city: "Nashville",
    country: "US",
    timezone: "America/Chicago",
  },
  RNO: {
    code: "RNO",
    name: "Reno–Tahoe International Airport",
    city: "Reno",
    country: "US",
    timezone: "America/Los_Angeles",
  },
  PDX: {
    code: "PDX",
    name: "Portland International Airport",
    city: "Portland",
    country: "US",
    timezone: "America/Los_Angeles",
  },
  SNA: {
    code: "SNA",
    name: "John Wayne Airport",
    city: "Santa Ana",
    country: "US",
    timezone: "America/Los_Angeles",
  },
  ONT: {
    code: "ONT",
    name: "Ontario International Airport",
    city: "Ontario",
    country: "US",
    timezone: "America/Los_Angeles",
  },
  BUR: {
    code: "BUR",
    name: "Hollywood Burbank Airport",
    city: "Burbank",
    country: "US",
    timezone: "America/Los_Angeles",
  },
  OMA: {
    code: "OMA",
    name: "Eppley Airfield",
    city: "Omaha",
    country: "US",
    timezone: "America/Chicago",
  },
  MCI: {
    code: "MCI",
    name: "Kansas City International Airport",
    city: "Kansas City",
    country: "US",
    timezone: "America/Chicago",
  },
  TUL: {
    code: "TUL",
    name: "Tulsa International Airport",
    city: "Tulsa",
    country: "US",
    timezone: "America/Chicago",
  },
  SAT: {
    code: "SAT",
    name: "San Antonio International Airport",
    city: "San Antonio",
    country: "US",
    timezone: "America/Chicago",
  },
  ABQ: {
    code: "ABQ",
    name: "Albuquerque International Sunport",
    city: "Albuquerque",
    country: "US",
    timezone: "America/Denver",
  },
  BOI: {
    code: "BOI",
    name: "Boise Airport",
    city: "Boise",
    country: "US",
    timezone: "America/Boise",
  },
  GEG: {
    code: "GEG",
    name: "Spokane International Airport",
    city: "Spokane",
    country: "US",
    timezone: "America/Los_Angeles",
  },
  BDL: {
    code: "BDL",
    name: "Bradley International Airport",
    city: "Hartford",
    country: "US",
    timezone: "America/New_York",
  },
  SJU: {
    code: "SJU",
    name: "Luis Muñoz Marín International Airport",
    city: "San Juan",
    country: "PR",
    timezone: "America/Puerto_Rico",
  },

  // --- Canada ---
  YYZ: {
    code: "YYZ",
    name: "Toronto Pearson International Airport",
    city: "Toronto",
    country: "CA",
    timezone: "America/Toronto",
  },
  YVR: {
    code: "YVR",
    name: "Vancouver International Airport",
    city: "Vancouver",
    country: "CA",
    timezone: "America/Vancouver",
  },
  YYC: {
    code: "YYC",
    name: "Calgary International Airport",
    city: "Calgary",
    country: "CA",
    timezone: "America/Edmonton",
  },
  YUL: {
    code: "YUL",
    name: "Montréal–Trudeau International Airport",
    city: "Montreal",
    country: "CA",
    timezone: "America/Toronto",
  },
  YOW: {
    code: "YOW",
    name: "Ottawa Macdonald–Cartier International Airport",
    city: "Ottawa",
    country: "CA",
    timezone: "America/Toronto",
  },
  YEG: {
    code: "YEG",
    name: "Edmonton International Airport",
    city: "Edmonton",
    country: "CA",
    timezone: "America/Edmonton",
  },
  YHZ: {
    code: "YHZ",
    name: "Halifax Stanfield International Airport",
    city: "Halifax",
    country: "CA",
    timezone: "America/Halifax",
  },

  // --- Europe: Major Hubs ---
  LHR: {
    code: "LHR",
    name: "London Heathrow Airport",
    city: "London",
    country: "UK",
    timezone: "Europe/London",
  },
  LGW: {
    code: "LGW",
    name: "London Gatwick Airport",
    city: "London",
    country: "UK",
    timezone: "Europe/London",
  },
  MAN: {
    code: "MAN",
    name: "Manchester Airport",
    city: "Manchester",
    country: "UK",
    timezone: "Europe/London",
  },
  DUB: {
    code: "DUB",
    name: "Dublin Airport",
    city: "Dublin",
    country: "IE",
    timezone: "Europe/Dublin",
  },
  CDG: {
    code: "CDG",
    name: "Charles de Gaulle Airport",
    city: "Paris",
    country: "FR",
    timezone: "Europe/Paris",
  },
  ORY: {
    code: "ORY",
    name: "Paris Orly Airport",
    city: "Paris",
    country: "FR",
    timezone: "Europe/Paris",
  },
  FRA: {
    code: "FRA",
    name: "Frankfurt Airport",
    city: "Frankfurt",
    country: "DE",
    timezone: "Europe/Berlin",
  },
  MUC: {
    code: "MUC",
    name: "Munich Airport",
    city: "Munich",
    country: "DE",
    timezone: "Europe/Berlin",
  },
  BER: {
    code: "BER",
    name: "Berlin Brandenburg Airport",
    city: "Berlin",
    country: "DE",
    timezone: "Europe/Berlin",
  },
  AMS: {
    code: "AMS",
    name: "Amsterdam Schiphol Airport",
    city: "Amsterdam",
    country: "NL",
    timezone: "Europe/Amsterdam",
  },
  BRU: {
    code: "BRU",
    name: "Brussels Airport",
    city: "Brussels",
    country: "BE",
    timezone: "Europe/Brussels",
  },
  MAD: {
    code: "MAD",
    name: "Adolfo Suárez Madrid–Barajas Airport",
    city: "Madrid",
    country: "ES",
    timezone: "Europe/Madrid",
  },
  BCN: {
    code: "BCN",
    name: "Barcelona–El Prat Airport",
    city: "Barcelona",
    country: "ES",
    timezone: "Europe/Madrid",
  },
  LIS: {
    code: "LIS",
    name: "Humberto Delgado Airport",
    city: "Lisbon",
    country: "PT",
    timezone: "Europe/Lisbon",
  },
  FCO: {
    code: "FCO",
    name: "Rome Fiumicino Airport",
    city: "Rome",
    country: "IT",
    timezone: "Europe/Rome",
  },
  MXP: {
    code: "MXP",
    name: "Milan Malpensa Airport",
    city: "Milan",
    country: "IT",
    timezone: "Europe/Rome",
  },
  ZRH: {
    code: "ZRH",
    name: "Zürich Airport",
    city: "Zürich",
    country: "CH",
    timezone: "Europe/Zurich",
  },
  GVA: {
    code: "GVA",
    name: "Geneva Airport",
    city: "Geneva",
    country: "CH",
    timezone: "Europe/Zurich",
  },
  CPH: {
    code: "CPH",
    name: "Copenhagen Airport",
    city: "Copenhagen",
    country: "DK",
    timezone: "Europe/Copenhagen",
  },
  OSL: {
    code: "OSL",
    name: "Oslo Gardermoen Airport",
    city: "Oslo",
    country: "NO",
    timezone: "Europe/Oslo",
  },
  ARN: {
    code: "ARN",
    name: "Stockholm Arlanda Airport",
    city: "Stockholm",
    country: "SE",
    timezone: "Europe/Stockholm",
  },
  HEL: {
    code: "HEL",
    name: "Helsinki Airport",
    city: "Helsinki",
    country: "FI",
    timezone: "Europe/Helsinki",
  },
  VIE: {
    code: "VIE",
    name: "Vienna International Airport",
    city: "Vienna",
    country: "AT",
    timezone: "Europe/Vienna",
  },
  PRG: {
    code: "PRG",
    name: "Václav Havel Airport Prague",
    city: "Prague",
    country: "CZ",
    timezone: "Europe/Prague",
  },
  WAW: {
    code: "WAW",
    name: "Warsaw Chopin Airport",
    city: "Warsaw",
    country: "PL",
    timezone: "Europe/Warsaw",
  },
  ATH: {
    code: "ATH",
    name: "Athens International Airport",
    city: "Athens",
    country: "GR",
    timezone: "Europe/Athens",
  },

  // --- Middle East & Africa ---
  DXB: {
    code: "DXB",
    name: "Dubai International Airport",
    city: "Dubai",
    country: "AE",
    timezone: "Asia/Dubai",
  },
  DWC: {
    code: "DWC",
    name: "Al Maktoum International Airport",
    city: "Dubai",
    country: "AE",
    timezone: "Asia/Dubai",
  },
  DOH: {
    code: "DOH",
    name: "Hamad International Airport",
    city: "Doha",
    country: "QA",
    timezone: "Asia/Qatar",
  },
  RUH: {
    code: "RUH",
    name: "King Khalid International Airport",
    city: "Riyadh",
    country: "SA",
    timezone: "Asia/Riyadh",
  },
  JED: {
    code: "JED",
    name: "King Abdulaziz International Airport",
    city: "Jeddah",
    country: "SA",
    timezone: "Asia/Riyadh",
  },
  CAI: {
    code: "CAI",
    name: "Cairo International Airport",
    city: "Cairo",
    country: "EG",
    timezone: "Africa/Cairo",
  },
  JNB: {
    code: "JNB",
    name: "O. R. Tambo International Airport",
    city: "Johannesburg",
    country: "ZA",
    timezone: "Africa/Johannesburg",
  },
  CPT: {
    code: "CPT",
    name: "Cape Town International Airport",
    city: "Cape Town",
    country: "ZA",
    timezone: "Africa/Johannesburg",
  },
  ADD: {
    code: "ADD",
    name: "Addis Ababa Bole International Airport",
    city: "Addis Ababa",
    country: "ET",
    timezone: "Africa/Addis_Ababa",
  },

  // --- Asia / Pacific ---
  HND: {
    code: "HND",
    name: "Tokyo Haneda Airport",
    city: "Tokyo",
    country: "JP",
    timezone: "Asia/Tokyo",
  },
  NRT: {
    code: "NRT",
    name: "Narita International Airport",
    city: "Tokyo",
    country: "JP",
    timezone: "Asia/Tokyo",
  },
  KIX: {
    code: "KIX",
    name: "Kansai International Airport",
    city: "Osaka",
    country: "JP",
    timezone: "Asia/Tokyo",
  },
  ICN: {
    code: "ICN",
    name: "Incheon International Airport",
    city: "Seoul",
    country: "KR",
    timezone: "Asia/Seoul",
  },
  GMP: {
    code: "GMP",
    name: "Gimpo International Airport",
    city: "Seoul",
    country: "KR",
    timezone: "Asia/Seoul",
  },
  HKG: {
    code: "HKG",
    name: "Hong Kong International Airport",
    city: "Hong Kong",
    country: "HK",
    timezone: "Asia/Hong_Kong",
  },
  TPE: {
    code: "TPE",
    name: "Taoyuan International Airport",
    city: "Taipei",
    country: "TW",
    timezone: "Asia/Taipei",
  },
  PVG: {
    code: "PVG",
    name: "Shanghai Pudong International Airport",
    city: "Shanghai",
    country: "CN",
    timezone: "Asia/Shanghai",
  },
  SHA: {
    code: "SHA",
    name: "Shanghai Hongqiao International Airport",
    city: "Shanghai",
    country: "CN",
    timezone: "Asia/Shanghai",
  },
  PEK: {
    code: "PEK",
    name: "Beijing Capital International Airport",
    city: "Beijing",
    country: "CN",
    timezone: "Asia/Shanghai",
  },
  PKX: {
    code: "PKX",
    name: "Beijing Daxing International Airport",
    city: "Beijing",
    country: "CN",
    timezone: "Asia/Shanghai",
  },
  CAN: {
    code: "CAN",
    name: "Guangzhou Baiyun International Airport",
    city: "Guangzhou",
    country: "CN",
    timezone: "Asia/Shanghai",
  },
  SIN: {
    code: "SIN",
    name: "Singapore Changi Airport",
    city: "Singapore",
    country: "SG",
    timezone: "Asia/Singapore",
  },
  KUL: {
    code: "KUL",
    name: "Kuala Lumpur International Airport",
    city: "Kuala Lumpur",
    country: "MY",
    timezone: "Asia/Kuala_Lumpur",
  },
  BKK: {
    code: "BKK",
    name: "Suvarnabhumi Airport",
    city: "Bangkok",
    country: "TH",
    timezone: "Asia/Bangkok",
  },
  DMK: {
    code: "DMK",
    name: "Don Mueang International Airport",
    city: "Bangkok",
    country: "TH",
    timezone: "Asia/Bangkok",
  },
  DEL: {
    code: "DEL",
    name: "Indira Gandhi International Airport",
    city: "Delhi",
    country: "IN",
    timezone: "Asia/Kolkata",
  },
  BOM: {
    code: "BOM",
    name: "Chhatrapati Shivaji Maharaj International Airport",
    city: "Mumbai",
    country: "IN",
    timezone: "Asia/Kolkata",
  },
  BLR: {
    code: "BLR",
    name: "Kempegowda International Airport",
    city: "Bengaluru",
    country: "IN",
    timezone: "Asia/Kolkata",
  },
  MAA: {
    code: "MAA",
    name: "Chennai International Airport",
    city: "Chennai",
    country: "IN",
    timezone: "Asia/Kolkata",
  },
  CGK: {
    code: "CGK",
    name: "Soekarno–Hatta International Airport",
    city: "Jakarta",
    country: "ID",
    timezone: "Asia/Jakarta",
  },
  DPS: {
    code: "DPS",
    name: "Ngurah Rai International Airport",
    city: "Denpasar (Bali)",
    country: "ID",
    timezone: "Asia/Makassar",
  },
  SYD: {
    code: "SYD",
    name: "Sydney Kingsford Smith Airport",
    city: "Sydney",
    country: "AU",
    timezone: "Australia/Sydney",
  },
  MEL: {
    code: "MEL",
    name: "Melbourne Airport",
    city: "Melbourne",
    country: "AU",
    timezone: "Australia/Melbourne",
  },
  BNE: {
    code: "BNE",
    name: "Brisbane Airport",
    city: "Brisbane",
    country: "AU",
    timezone: "Australia/Brisbane",
  },
  PER: {
    code: "PER",
    name: "Perth Airport",
    city: "Perth",
    country: "AU",
    timezone: "Australia/Perth",
  },
  AKL: {
    code: "AKL",
    name: "Auckland Airport",
    city: "Auckland",
    country: "NZ",
    timezone: "Pacific/Auckland",
  },
  CHC: {
    code: "CHC",
    name: "Christchurch Airport",
    city: "Christchurch",
    country: "NZ",
    timezone: "Pacific/Auckland",
  },

  // --- Mexico / Latin America ---
  MEX: {
    code: "MEX",
    name: "Mexico City International Airport",
    city: "Mexico City",
    country: "MX",
    timezone: "America/Mexico_City",
  },
  CUN: {
    code: "CUN",
    name: "Cancún International Airport",
    city: "Cancún",
    country: "MX",
    timezone: "America/Cancun",
  },
  SJD: {
    code: "SJD",
    name: "Los Cabos International Airport",
    city: "San José del Cabo",
    country: "MX",
    timezone: "America/Mazatlan",
  },
  GDL: {
    code: "GDL",
    name: "Guadalajara International Airport",
    city: "Guadalajara",
    country: "MX",
    timezone: "America/Mexico_City",
  },
  PVR: {
    code: "PVR",
    name: "Licenciado Gustavo Díaz Ordaz International Airport",
    city: "Puerto Vallarta",
    country: "MX",
    timezone: "America/Mexico_City",
  },
  BOG: {
    code: "BOG",
    name: "El Dorado International Airport",
    city: "Bogotá",
    country: "CO",
    timezone: "America/Bogota",
  },
  MDE: {
    code: "MDE",
    name: "José María Córdova International Airport",
    city: "Medellín",
    country: "CO",
    timezone: "America/Bogota",
  },
  LIM: {
    code: "LIM",
    name: "Jorge Chávez International Airport",
    city: "Lima",
    country: "PE",
    timezone: "America/Lima",
  },
  SCL: {
    code: "SCL",
    name: "Comodoro Arturo Merino Benítez International Airport",
    city: "Santiago",
    country: "CL",
    timezone: "America/Santiago",
  },
  EZE: {
    code: "EZE",
    name: "Ezeiza International Airport",
    city: "Buenos Aires",
    country: "AR",
    timezone: "America/Argentina/Buenos_Aires",
  },
  GRU: {
    code: "GRU",
    name: "São Paulo/Guarulhos International Airport",
    city: "São Paulo",
    country: "BR",
    timezone: "America/Sao_Paulo",
  },
  GIG: {
    code: "GIG",
    name: "Rio de Janeiro–Galeão International Airport",
    city: "Rio de Janeiro",
    country: "BR",
    timezone: "America/Sao_Paulo",
  },
  PTY: {
    code: "PTY",
    name: "Tocumen International Airport",
    city: "Panama City",
    country: "PA",
    timezone: "America/Panama",
  },
  SDQ: {
    code: "SDQ",
    name: "Las Américas International Airport",
    city: "Santo Domingo",
    country: "DO",
    timezone: "America/Santo_Domingo",
  },
  PUJ: {
    code: "PUJ",
    name: "Punta Cana International Airport",
    city: "Punta Cana",
    country: "DO",
    timezone: "America/Santo_Domingo",
  },
};

// --------------------------------------
// Reverse Mapping: Name -> Airport
// --------------------------------------

const AIRPORTS_BY_NAME: Record<string, Airport> = Object.values(
  AIRPORTS_BY_CODE
).reduce((acc, airport) => {
  acc[airport.name.toLowerCase()] = airport;
  return acc;
}, {} as Record<string, Airport>);

// --------------------------------------
// Utility Helpers
// --------------------------------------

function getAirportByCode(code: string): Airport | null {
  if (!code) return null;
  return AIRPORTS_BY_CODE[code.toUpperCase()] ?? null;
}

function getAirportByName(name: string): Airport | null {
  if (!name) return null;
  return AIRPORTS_BY_NAME[name.trim().toLowerCase()] ?? null;
}

/** Best-effort resolver from either code or name */
function resolveAirport(input: string): Airport | null {
  if (!input) return null;

  const byCode = getAirportByCode(input);
  if (byCode) return byCode;

  const normalized = input.trim().toLowerCase();
  return getAirportByName(normalized) ?? null;
}
